credentials:
  usernames:
    ajaxxx:
      email: asmaa@example.com
      name: Ajaxxx
      password: "$2b$12$Wiq2qDINo4eSEdWizFDT3u4ROyYJNR9B9mwzHA49U6DbN/NGwAEOS"
    testuser:
      email: test@example.com
      name: Test User
      password: "$2b$12$abc123abc123abc123abc123abc123abc123abc123abc123abc123"

cookie:
  expiry_days: 30
  key: "random_signature_key"
  name: "gym_auth_cookie"